spring:
  application:
    name: micromarket
  datasource: 
    url: jdbc:mysql://localhost:3306/micromarket
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:                              # ← faltaba este nivel
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:                                    # ← debe estar dentro de spring:
    serialization:
      indent-output: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 9090
